/*
 * Copyright (C) 2018, Jason Parker
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

#ifndef _INPUT_H
//#define _INPUT_H

#if defined(HAVE_EVDEV)
#include "input-evdev.h"

#define hl_input_init(...) hl_evdev_init(__VA_ARGS__)
#define hl_input_inject(id, type, code, value) hl_evdev_inject(id, type, code, value)
#else
#include "input-defines.h"

#define hl_input_init(...)
#define hl_input_inject(id, type, code, value)
#endif

#define CODELOOKUP(type, key) { #type, #key, type, key }
#define KEYLOOKUP(key) CODELOOKUP(EV_KEY, key)
#define ABSLOOKUP(key) CODELOOKUP(EV_ABS, key)
#define RELLOOKUP(key) CODELOOKUP(EV_REL, key)

#define CODETABLE \
	/* Mouse */\
	KEYLOOKUP(BTN_LEFT),\
	KEYLOOKUP(BTN_RIGHT),\
	KEYLOOKUP(BTN_MIDDLE),\
	KEYLOOKUP(BTN_SIDE),\
	KEYLOOKUP(BTN_EXTRA),\
	KEYLOOKUP(BTN_LEFT),\
	KEYLOOKUP(BTN_RIGHT),\
	KEYLOOKUP(BTN_MIDDLE),\
	KEYLOOKUP(BTN_SIDE),\
	KEYLOOKUP(BTN_EXTRA),\
	KEYLOOKUP(BTN_FORWARD),\
	KEYLOOKUP(BTN_BACK),\
	KEYLOOKUP(BTN_TASK),\
	/* Gamepad */\
	KEYLOOKUP(BTN_SOUTH),\
	KEYLOOKUP(BTN_A),\
	KEYLOOKUP(BTN_EAST),\
	KEYLOOKUP(BTN_B),\
	KEYLOOKUP(BTN_C),\
	KEYLOOKUP(BTN_NORTH),\
	KEYLOOKUP(BTN_X),\
	KEYLOOKUP(BTN_WEST),\
	KEYLOOKUP(BTN_Y),\
	KEYLOOKUP(BTN_Z),\
	KEYLOOKUP(BTN_TL),\
	KEYLOOKUP(BTN_TR),\
	KEYLOOKUP(BTN_TL2),\
	KEYLOOKUP(BTN_TR2),\
	KEYLOOKUP(BTN_SELECT),\
	KEYLOOKUP(BTN_START),\
	KEYLOOKUP(BTN_MODE),\
	KEYLOOKUP(BTN_THUMBL),\
	KEYLOOKUP(BTN_THUMBR),\
	KEYLOOKUP(BTN_DPAD_UP),\
	KEYLOOKUP(BTN_DPAD_DOWN),\
	KEYLOOKUP(BTN_DPAD_LEFT),\
	KEYLOOKUP(BTN_DPAD_RIGHT),\
	/* Keyboard */\
	KEYLOOKUP(KEY_ESC),\
	KEYLOOKUP(KEY_1),\
	KEYLOOKUP(KEY_2),\
	KEYLOOKUP(KEY_3),\
	KEYLOOKUP(KEY_4),\
	KEYLOOKUP(KEY_5),\
	KEYLOOKUP(KEY_6),\
	KEYLOOKUP(KEY_7),\
	KEYLOOKUP(KEY_8),\
	KEYLOOKUP(KEY_9),\
	KEYLOOKUP(KEY_0),\
	KEYLOOKUP(KEY_MINUS),\
	KEYLOOKUP(KEY_EQUAL),\
	KEYLOOKUP(KEY_BACKSPACE),\
	KEYLOOKUP(KEY_TAB),\
	KEYLOOKUP(KEY_Q),\
	KEYLOOKUP(KEY_W),\
	KEYLOOKUP(KEY_E),\
	KEYLOOKUP(KEY_R),\
	KEYLOOKUP(KEY_T),\
	KEYLOOKUP(KEY_Y),\
	KEYLOOKUP(KEY_U),\
	KEYLOOKUP(KEY_I),\
	KEYLOOKUP(KEY_O),\
	KEYLOOKUP(KEY_P),\
	KEYLOOKUP(KEY_LEFTBRACE),\
	KEYLOOKUP(KEY_RIGHTBRACE),\
	KEYLOOKUP(KEY_ENTER),\
	KEYLOOKUP(KEY_LEFTCTRL),\
	KEYLOOKUP(KEY_A),\
	KEYLOOKUP(KEY_S),\
	KEYLOOKUP(KEY_D),\
	KEYLOOKUP(KEY_F),\
	KEYLOOKUP(KEY_G),\
	KEYLOOKUP(KEY_H),\
	KEYLOOKUP(KEY_J),\
	KEYLOOKUP(KEY_K),\
	KEYLOOKUP(KEY_L),\
	KEYLOOKUP(KEY_SEMICOLON),\
	KEYLOOKUP(KEY_APOSTROPHE),\
	KEYLOOKUP(KEY_GRAVE),\
	KEYLOOKUP(KEY_LEFTSHIFT),\
	KEYLOOKUP(KEY_BACKSLASH),\
	KEYLOOKUP(KEY_Z),\
	KEYLOOKUP(KEY_X),\
	KEYLOOKUP(KEY_C),\
	KEYLOOKUP(KEY_V),\
	KEYLOOKUP(KEY_B),\
	KEYLOOKUP(KEY_N),\
	KEYLOOKUP(KEY_M),\
	KEYLOOKUP(KEY_COMMA),\
	KEYLOOKUP(KEY_DOT),\
	KEYLOOKUP(KEY_SLASH),\
	KEYLOOKUP(KEY_RIGHTSHIFT),\
	KEYLOOKUP(KEY_KPASTERISK),\
	KEYLOOKUP(KEY_LEFTALT),\
	KEYLOOKUP(KEY_SPACE),\
	KEYLOOKUP(KEY_CAPSLOCK),\
	KEYLOOKUP(KEY_F1),\
	KEYLOOKUP(KEY_F2),\
	KEYLOOKUP(KEY_F3),\
	KEYLOOKUP(KEY_F4),\
	KEYLOOKUP(KEY_F5),\
	KEYLOOKUP(KEY_F6),\
	KEYLOOKUP(KEY_F7),\
	KEYLOOKUP(KEY_F8),\
	KEYLOOKUP(KEY_F9),\
	KEYLOOKUP(KEY_F10),\
	KEYLOOKUP(KEY_NUMLOCK),\
	KEYLOOKUP(KEY_SCROLLLOCK),\
	KEYLOOKUP(KEY_KP7),\
	KEYLOOKUP(KEY_KP8),\
	KEYLOOKUP(KEY_KP9),\
	KEYLOOKUP(KEY_KPMINUS),\
	KEYLOOKUP(KEY_KP4),\
	KEYLOOKUP(KEY_KP5),\
	KEYLOOKUP(KEY_KP6),\
	KEYLOOKUP(KEY_KPPLUS),\
	KEYLOOKUP(KEY_KP1),\
	KEYLOOKUP(KEY_KP2),\
	KEYLOOKUP(KEY_KP3),\
	KEYLOOKUP(KEY_KP0),\
	KEYLOOKUP(KEY_KPDOT),\
	KEYLOOKUP(KEY_ZENKAKUHANKAKU),\
	KEYLOOKUP(KEY_102ND),\
	KEYLOOKUP(KEY_F11),\
	KEYLOOKUP(KEY_F12),\
	KEYLOOKUP(KEY_RO),\
	KEYLOOKUP(KEY_KATAKANA),\
	KEYLOOKUP(KEY_HIRAGANA),\
	KEYLOOKUP(KEY_HENKAN),\
	KEYLOOKUP(KEY_KATAKANAHIRAGANA),\
	KEYLOOKUP(KEY_MUHENKAN),\
	KEYLOOKUP(KEY_KPJPCOMMA),\
	KEYLOOKUP(KEY_KPENTER),\
	KEYLOOKUP(KEY_RIGHTCTRL),\
	KEYLOOKUP(KEY_KPSLASH),\
	KEYLOOKUP(KEY_SYSRQ),\
	KEYLOOKUP(KEY_RIGHTALT),\
	KEYLOOKUP(KEY_HOME),\
	KEYLOOKUP(KEY_UP),\
	KEYLOOKUP(KEY_PAGEUP),\
	KEYLOOKUP(KEY_LEFT),\
	KEYLOOKUP(KEY_RIGHT),\
	KEYLOOKUP(KEY_END),\
	KEYLOOKUP(KEY_DOWN),\
	KEYLOOKUP(KEY_PAGEDOWN),\
	KEYLOOKUP(KEY_INSERT),\
	KEYLOOKUP(KEY_DELETE),\
	KEYLOOKUP(KEY_MUTE),\
	KEYLOOKUP(KEY_VOLUMEDOWN),\
	KEYLOOKUP(KEY_VOLUMEUP),\
	KEYLOOKUP(KEY_POWER),\
	KEYLOOKUP(KEY_KPEQUAL),\
	KEYLOOKUP(KEY_PAUSE),\
	KEYLOOKUP(KEY_KPCOMMA),\
	KEYLOOKUP(KEY_HANGEUL),\
	KEYLOOKUP(KEY_HANJA),\
	KEYLOOKUP(KEY_YEN),\
	KEYLOOKUP(KEY_LEFTMETA),\
	KEYLOOKUP(KEY_RIGHTMETA),\
	KEYLOOKUP(KEY_COMPOSE),\
	KEYLOOKUP(KEY_STOP),\
	KEYLOOKUP(KEY_AGAIN),\
	KEYLOOKUP(KEY_PROPS),\
	KEYLOOKUP(KEY_UNDO),\
	KEYLOOKUP(KEY_FRONT),\
	KEYLOOKUP(KEY_COPY),\
	KEYLOOKUP(KEY_OPEN),\
	KEYLOOKUP(KEY_PASTE),\
	KEYLOOKUP(KEY_FIND),\
	KEYLOOKUP(KEY_CUT),\
	KEYLOOKUP(KEY_HELP),\
	KEYLOOKUP(KEY_CALC),\
	KEYLOOKUP(KEY_SLEEP),\
	KEYLOOKUP(KEY_WWW),\
	KEYLOOKUP(KEY_COFFEE),\
	KEYLOOKUP(KEY_BACK),\
	KEYLOOKUP(KEY_FORWARD),\
	KEYLOOKUP(KEY_EJECTCD),\
	KEYLOOKUP(KEY_NEXTSONG),\
	KEYLOOKUP(KEY_PLAYPAUSE),\
	KEYLOOKUP(KEY_PREVIOUSSONG),\
	KEYLOOKUP(KEY_STOPCD),\
	KEYLOOKUP(KEY_REFRESH),\
	KEYLOOKUP(KEY_EDIT),\
	KEYLOOKUP(KEY_SCROLLUP),\
	KEYLOOKUP(KEY_SCROLLDOWN),\
	KEYLOOKUP(KEY_KPLEFTPAREN),\
	KEYLOOKUP(KEY_KPRIGHTPAREN),\
	KEYLOOKUP(KEY_F13),\
	KEYLOOKUP(KEY_F14),\
	KEYLOOKUP(KEY_F15),\
	KEYLOOKUP(KEY_F16),\
	KEYLOOKUP(KEY_F17),\
	KEYLOOKUP(KEY_F18),\
	KEYLOOKUP(KEY_F19),\
	KEYLOOKUP(KEY_F20),\
	KEYLOOKUP(KEY_F21),\
	KEYLOOKUP(KEY_F22),\
	KEYLOOKUP(KEY_F23),\
	KEYLOOKUP(KEY_F24),\
	KEYLOOKUP(KEY_MUTE),\
	KEYLOOKUP(KEY_VOLUMEDOWN),\
	KEYLOOKUP(KEY_VOLUMEUP),\
	KEYLOOKUP(KEY_POWER),\
	KEYLOOKUP(KEY_STOP),\
	KEYLOOKUP(KEY_CALC),\
	KEYLOOKUP(KEY_SLEEP),\
	KEYLOOKUP(KEY_WAKEUP),\
	KEYLOOKUP(KEY_FILE),\
	KEYLOOKUP(KEY_MAIL),\
	KEYLOOKUP(KEY_BOOKMARKS),\
	KEYLOOKUP(KEY_BACK),\
	KEYLOOKUP(KEY_FORWARD),\
	KEYLOOKUP(KEY_NEXTSONG),\
	KEYLOOKUP(KEY_PLAYPAUSE),\
	KEYLOOKUP(KEY_PREVIOUSSONG),\
	KEYLOOKUP(KEY_STOPCD),\
	KEYLOOKUP(KEY_CONFIG),\
	KEYLOOKUP(KEY_HOMEPAGE),\
	KEYLOOKUP(KEY_REFRESH),\
	KEYLOOKUP(KEY_SEARCH),\
	KEYLOOKUP(KEY_WORDPROCESSOR),\
	KEYLOOKUP(KEY_SPREADSHEET),\
	KEYLOOKUP(KEY_PRESENTATION),\
	/* Axes */\
	ABSLOOKUP(ABS_X),\
	ABSLOOKUP(ABS_Y),\
	ABSLOOKUP(ABS_Z),\
	ABSLOOKUP(ABS_RX),\
	ABSLOOKUP(ABS_RY),\
	ABSLOOKUP(ABS_RZ),\
	ABSLOOKUP(ABS_THROTTLE),\
	ABSLOOKUP(ABS_RUDDER),\
	ABSLOOKUP(ABS_WHEEL),\
	ABSLOOKUP(ABS_GAS),\
	ABSLOOKUP(ABS_BRAKE),\
	/* Hats */\
	ABSLOOKUP(ABS_HAT0X),\
	ABSLOOKUP(ABS_HAT0Y),\
	ABSLOOKUP(ABS_HAT1X),\
	ABSLOOKUP(ABS_HAT1Y),\
	ABSLOOKUP(ABS_HAT2X),\
	ABSLOOKUP(ABS_HAT2Y),\
	ABSLOOKUP(ABS_HAT3X),\
	ABSLOOKUP(ABS_HAT3Y),\
	/* Relative axes */\
	RELLOOKUP(REL_X),\
	RELLOOKUP(REL_Y),\
	RELLOOKUP(REL_Z),\
	RELLOOKUP(REL_RX),\
	RELLOOKUP(REL_RY),\
	RELLOOKUP(REL_RZ),\
	RELLOOKUP(REL_HWHEEL),\
	RELLOOKUP(REL_DIAL),\
	RELLOOKUP(REL_WHEEL),\
	RELLOOKUP(REL_MISC)

struct codelookup {
	const char *typestr;
	const char *codestr;
	const uint8_t type;
	const uint16_t code;
} codelookups[] = {
	CODETABLE
};

#endif
